# Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
# Your use of Altera Corporation's design tools, logic functions 
# and other software and tools, and its AMPP partner logic 
# functions, and any output files from any of the foregoing 
# (including device programming or simulation files), and any 
# associated documentation or information are expressly subject 
# to the terms and conditions of the Altera Program License 
# Subscription Agreement, the Altera Quartus II License Agreement,
# the Altera MegaCore Function License Agreement, or other 
# applicable license agreement, including, without limitation, 
# that your use is for the sole purpose of programming logic 
# devices manufactured by Altera and sold by Altera or its 
# authorized distributors.  Please refer to the applicable 
# agreement for further details.

# Quartus II 64-Bit Version 15.0.0 Build 145 04/22/2015 SJ Full Version
# File: E:\svn\AX845_new\full_test\par_altera\top.tcl
# Generated on: Tue Jan 12 20:16:59 2016

package require ::quartus::project

set_location_assignment PIN_V7 -to mem_we_n
set_location_assignment PIN_T10 -to mem_ras_n
set_location_assignment PIN_R16 -to mem_odt[0]
set_location_assignment PIN_V13 -to mem_dqs[3]
set_location_assignment PIN_Y13 -to mem_dqs[2]
set_location_assignment PIN_AB9 -to mem_dqs[1]
set_location_assignment PIN_V10 -to mem_dqs[0]
set_location_assignment PIN_AB18 -to mem_dq[31]
set_location_assignment PIN_W15 -to mem_dq[30]
set_location_assignment PIN_AB20 -to mem_dq[29]
set_location_assignment PIN_V14 -to mem_dq[28]
set_location_assignment PIN_AB16 -to mem_dq[27]
set_location_assignment PIN_W17 -to mem_dq[26]
set_location_assignment PIN_V15 -to mem_dq[25]
set_location_assignment PIN_T15 -to mem_dq[24]
set_location_assignment PIN_AA15 -to mem_dq[23]
set_location_assignment PIN_U12 -to mem_dq[22]
set_location_assignment PIN_AA14 -to mem_dq[21]
set_location_assignment PIN_AB13 -to mem_dq[20]
set_location_assignment PIN_AA13 -to mem_dq[19]
set_location_assignment PIN_AB14 -to mem_dq[18]
set_location_assignment PIN_W13 -to mem_dq[17]
set_location_assignment PIN_AB15 -to mem_dq[16]
set_location_assignment PIN_W10 -to mem_dq[15]
set_location_assignment PIN_Y8 -to mem_dq[14]
set_location_assignment PIN_V11 -to mem_dq[13]
set_location_assignment PIN_AB7 -to mem_dq[12]
set_location_assignment PIN_AA8 -to mem_dq[11]
set_location_assignment PIN_Y10 -to mem_dq[10]
set_location_assignment PIN_AB8 -to mem_dq[9]
set_location_assignment PIN_AA9 -to mem_dq[8]
set_location_assignment PIN_U9 -to mem_dq[7]
set_location_assignment PIN_AA5 -to mem_dq[6]
set_location_assignment PIN_Y7 -to mem_dq[5]
set_location_assignment PIN_Y3 -to mem_dq[4]
set_location_assignment PIN_W7 -to mem_dq[3]
set_location_assignment PIN_W8 -to mem_dq[2]
set_location_assignment PIN_W6 -to mem_dq[1]
set_location_assignment PIN_V8 -to mem_dq[0]
set_location_assignment PIN_AA16 -to mem_dm[3]
set_location_assignment PIN_AA10 -to mem_dm[2]
set_location_assignment PIN_AA7 -to mem_dm[1]
set_location_assignment PIN_V5 -to mem_dm[0]
set_location_assignment PIN_Y17 -to mem_cs_n[0]
set_location_assignment PIN_AB17 -to mem_clk_n[0]
set_location_assignment PIN_AA17 -to mem_clk[0]
set_location_assignment PIN_U8 -to mem_cke[0]
set_location_assignment PIN_R15 -to mem_cas_n
set_location_assignment PIN_T9 -to mem_ba[2]
set_location_assignment PIN_AB10 -to mem_ba[1]
set_location_assignment PIN_U7 -to mem_ba[0]
set_location_assignment PIN_U14 -to mem_addr[12]
set_location_assignment PIN_AB3 -to mem_addr[11]
set_location_assignment PIN_V6 -to mem_addr[10]
set_location_assignment PIN_U13 -to mem_addr[9]
set_location_assignment PIN_AA3 -to mem_addr[8]
set_location_assignment PIN_T14 -to mem_addr[7]
set_location_assignment PIN_AB5 -to mem_addr[6]
set_location_assignment PIN_T11 -to mem_addr[5]
set_location_assignment PIN_AA4 -to mem_addr[4]
set_location_assignment PIN_R14 -to mem_addr[3]
set_location_assignment PIN_T16 -to mem_addr[2]
set_location_assignment PIN_Y6 -to mem_addr[1]
set_location_assignment PIN_U10 -to mem_addr[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_odt[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_odt[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_clk[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_clk[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_clk_n[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_clk_n[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_cs_n[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_cs_n[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_cke[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_cke[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[3]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[4]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[4]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[5]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[5]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[6]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[6]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[7]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[7]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[8]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[8]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[9]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[9]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[10]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[10]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[11]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[11]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_addr[12]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_addr[12]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_ba[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_ba[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_ba[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_ba[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_ba[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_ba[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_ras_n
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_ras_n
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_cas_n
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_cas_n
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_we_n
set_instance_assignment -name CURRENT_STRENGTH_NEW "MAXIMUM CURRENT" -to mem_we_n
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[3]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[4]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[4]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[5]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[5]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[6]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[6]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[7]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[7]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[8]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[8]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[9]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[9]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[10]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[10]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[11]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[11]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[12]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[12]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[13]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[13]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[14]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[14]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[15]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[15]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[16]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[16]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[17]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[17]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[18]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[18]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[19]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[19]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[20]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[20]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[21]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[21]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[22]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[22]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[23]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[23]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[24]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[24]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[25]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[25]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[26]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[26]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[27]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[27]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[28]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[28]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[29]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[29]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[30]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[30]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dq[31]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dq[31]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dqs[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dqs[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dqs[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dqs[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dqs[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dqs[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dqs[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dqs[3]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dm[0]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dm[0]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dm[1]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dm[1]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dm[2]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dm[2]
set_instance_assignment -name IO_STANDARD "SSTL-18 CLASS I" -to mem_dm[3]
set_instance_assignment -name CURRENT_STRENGTH_NEW 12MA -to mem_dm[3]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[0]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[1]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[2]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[3]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[4]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[5]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[6]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[7]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[8]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[9]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[10]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[11]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[12]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[13]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[14]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[15]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[16]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[17]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[18]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[19]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[20]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[21]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[22]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[23]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[24]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[25]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[26]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[27]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[28]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[29]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[30]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dq[31]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dqs[0]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dqs[1]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dqs[2]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dqs[3]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dm[0]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dm[1]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dm[2]
set_instance_assignment -name OUTPUT_ENABLE_GROUP 3078784 -to mem_dm[3]
set_location_assignment PIN_T22 -to clk_27m
set_location_assignment PIN_T2 -to clk_50m
set_location_assignment PIN_B22 -to cmos_d[7]
set_location_assignment PIN_B21 -to cmos_d[6]
set_location_assignment PIN_C13 -to cmos_d[5]
set_location_assignment PIN_D13 -to cmos_d[4]
set_location_assignment PIN_A20 -to cmos_d[3]
set_location_assignment PIN_A13 -to cmos_d[2]
set_location_assignment PIN_B13 -to cmos_d[1]
set_location_assignment PIN_B20 -to cmos_d[0]
set_location_assignment PIN_B14 -to cmos_href
set_location_assignment PIN_B6 -to cmos_pclk
set_location_assignment PIN_E11 -to cmos_pwdn
set_location_assignment PIN_F11 -to cmos_reset
set_location_assignment PIN_F15 -to cmos_scl
set_location_assignment PIN_G16 -to cmos_sda
set_location_assignment PIN_A6 -to cmos_xclk
set_location_assignment PIN_A14 -to cmos_vsync
set_location_assignment PIN_P7 -to cvbs_in_data[7]
set_location_assignment PIN_W1 -to cvbs_in_data[6]
set_location_assignment PIN_N7 -to cvbs_in_data[5]
set_location_assignment PIN_W2 -to cvbs_in_data[4]
set_location_assignment PIN_T7 -to cvbs_in_data[3]
set_location_assignment PIN_Y1 -to cvbs_in_data[2]
set_location_assignment PIN_R7 -to cvbs_in_data[1]
set_location_assignment PIN_Y2 -to cvbs_in_data[0]
set_location_assignment PIN_AA11 -to cvbs_in_clkp
set_location_assignment PIN_AB11 -to cvbs_in_clkn
set_location_assignment PIN_Y22 -to vga_out_vs
set_location_assignment PIN_R19 -to vga_out_hs
set_location_assignment PIN_W21 -to vga_out_de
set_location_assignment PIN_W22 -to vga_out_data[11]
set_location_assignment PIN_R18 -to vga_out_data[10]
set_location_assignment PIN_U21 -to vga_out_data[9]
set_location_assignment PIN_V21 -to vga_out_data[8]
set_location_assignment PIN_U22 -to vga_out_data[7]
set_location_assignment PIN_V22 -to vga_out_data[6]
set_location_assignment PIN_U19 -to vga_out_data[5]
set_location_assignment PIN_P16 -to vga_out_data[4]
set_location_assignment PIN_U20 -to vga_out_data[3]
set_location_assignment PIN_P15 -to vga_out_data[2]
set_location_assignment PIN_P21 -to vga_out_data[1]
set_location_assignment PIN_R21 -to vga_out_data[0]
set_location_assignment PIN_Y21 -to vga_out_clk
set_location_assignment PIN_P22 -to sys_key1
set_location_assignment PIN_R22 -to sys_key0
set_location_assignment PIN_H1 -to sda
set_location_assignment PIN_F8 -to scl
set_location_assignment PIN_B15 -to hdmi_out_vs
set_location_assignment PIN_C21 -to hdmi_out_rgb_r[7]
set_location_assignment PIN_F16 -to hdmi_out_rgb_r[6]
set_location_assignment PIN_D22 -to hdmi_out_rgb_r[5]
set_location_assignment PIN_E16 -to hdmi_out_rgb_r[4]
set_location_assignment PIN_D21 -to hdmi_out_rgb_r[3]
set_location_assignment PIN_J17 -to hdmi_out_rgb_r[2]
set_location_assignment PIN_F17 -to hdmi_out_rgb_r[1]
set_location_assignment PIN_H16 -to hdmi_out_rgb_r[0]
set_location_assignment PIN_G17 -to hdmi_out_rgb_g[7]
set_location_assignment PIN_H15 -to hdmi_out_rgb_g[6]
set_location_assignment PIN_E22 -to hdmi_out_rgb_g[5]
set_location_assignment PIN_H14 -to hdmi_out_rgb_g[4]
set_location_assignment PIN_E21 -to hdmi_out_rgb_g[3]
set_location_assignment PIN_H22 -to hdmi_out_rgb_g[2]
set_location_assignment PIN_F14 -to hdmi_out_rgb_g[1]
set_location_assignment PIN_F21 -to hdmi_out_rgb_g[0]
set_location_assignment PIN_G15 -to hdmi_out_rgb_b[7]
set_location_assignment PIN_F22 -to hdmi_out_rgb_b[6]
set_location_assignment PIN_B18 -to hdmi_out_rgb_b[5]
set_location_assignment PIN_A18 -to hdmi_out_rgb_b[4]
set_location_assignment PIN_B16 -to hdmi_out_rgb_b[3]
set_location_assignment PIN_B17 -to hdmi_out_rgb_b[2]
set_location_assignment PIN_A16 -to hdmi_out_rgb_b[1]
set_location_assignment PIN_A17 -to hdmi_out_rgb_b[0]
set_location_assignment PIN_N17 -to hdmi_out_clk
set_location_assignment PIN_A15 -to hdmi_out_hs
set_location_assignment PIN_C22 -to hdmi_out_de
set_location_assignment PIN_N21 -to hdmi_in_vs
set_location_assignment PIN_M22 -to hdmi_in_hs
set_location_assignment PIN_N22 -to hdmi_in_de
set_location_assignment PIN_G18 -to hdmi_in_data[23]
set_location_assignment PIN_H19 -to hdmi_in_data[22]
set_location_assignment PIN_C19 -to hdmi_in_data[21]
set_location_assignment PIN_H20 -to hdmi_in_data[20]
set_location_assignment PIN_H21 -to hdmi_in_data[19]
set_location_assignment PIN_D19 -to hdmi_in_data[18]
set_location_assignment PIN_F20 -to hdmi_in_data[17]
set_location_assignment PIN_H17 -to hdmi_in_data[16]
set_location_assignment PIN_F19 -to hdmi_in_data[15]
set_location_assignment PIN_K17 -to hdmi_in_data[14]
set_location_assignment PIN_N18 -to hdmi_in_data[13]
set_location_assignment PIN_K18 -to hdmi_in_data[12]
set_location_assignment PIN_J22 -to hdmi_in_data[11]
set_location_assignment PIN_M20 -to hdmi_in_data[10]
set_location_assignment PIN_J21 -to hdmi_in_data[9]
set_location_assignment PIN_E15 -to hdmi_in_data[8]
set_location_assignment PIN_K22 -to hdmi_in_data[7]
set_location_assignment PIN_G14 -to hdmi_in_data[6]
set_location_assignment PIN_L22 -to hdmi_in_data[5]
set_location_assignment PIN_K21 -to hdmi_in_data[4]
set_location_assignment PIN_L21 -to hdmi_in_data[3]
set_location_assignment PIN_N20 -to hdmi_in_data[2]
set_location_assignment PIN_M21 -to hdmi_in_data[1]
set_location_assignment PIN_N19 -to hdmi_in_data[0]
set_location_assignment PIN_M19 -to hdmi_in_clk
set_location_assignment PIN_C3 -to e_txer
set_location_assignment PIN_E5 -to e_txen
set_location_assignment PIN_C7 -to e_txd[7]
set_location_assignment PIN_C4 -to e_txd[6]
set_location_assignment PIN_D10 -to e_txd[5]
set_location_assignment PIN_E3 -to e_txd[4]
set_location_assignment PIN_E4 -to e_txd[3]
set_location_assignment PIN_E10 -to e_txd[2]
set_location_assignment PIN_F1 -to e_txd[1]
set_location_assignment PIN_F2 -to e_txd[0]
set_location_assignment PIN_B9 -to e_txc
set_location_assignment PIN_B7 -to e_rxer
set_location_assignment PIN_A4 -to e_rxdv
set_location_assignment PIN_C1 -to e_rxd[7]
set_location_assignment PIN_B2 -to e_rxd[6]
set_location_assignment PIN_A8 -to e_rxd[5]
set_location_assignment PIN_B1 -to e_rxd[4]
set_location_assignment PIN_B3 -to e_rxd[3]
set_location_assignment PIN_B10 -to e_rxd[2]
set_location_assignment PIN_A3 -to e_rxd[1]
set_location_assignment PIN_A10 -to e_rxd[0]
set_location_assignment PIN_A9 -to e_rxc
set_location_assignment PIN_E6 -to e_reset
set_location_assignment PIN_B8 -to e_mdio
set_location_assignment PIN_A7 -to e_mdc
set_location_assignment PIN_B4 -to e_gtxc
set_location_assignment PIN_V4 -to led[0]
set_location_assignment PIN_T5 -to led[3]
set_location_assignment PIN_P6 -to led[2]
set_location_assignment PIN_V3 -to led[1]
set_instance_assignment -name IO_STANDARD "1.8 V" -to cvbs_in_clkn
set_instance_assignment -name IO_STANDARD "1.8 V" -to cvbs_in_clkp
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_de
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_hs
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_b[7]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_b[6]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_b[5]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_b[4]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_b[3]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_b[2]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_b[1]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_b[0]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_g[7]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_g[6]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_g[5]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_g[4]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_g[3]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_g[2]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_g[1]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_g[0]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_r[7]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_r[6]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_r[5]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_r[4]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_r[3]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_r[2]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_r[1]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_rgb_r[0]
set_instance_assignment -name FAST_OUTPUT_REGISTER ON -to hdmi_out_vs
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[23]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[22]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[21]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[20]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[19]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[18]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[17]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[16]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[15]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[14]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[13]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[12]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[11]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[10]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[9]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[8]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[7]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[6]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[5]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[4]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[3]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[2]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[1]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_data[0]
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_de
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_hs
set_instance_assignment -name FAST_INPUT_REGISTER ON -to hdmi_in_vs
set_instance_assignment -name CURRENT_STRENGTH_NEW 4MA -to vga_out_clk
