######################################################################
##
## Filename: tb_bt656.udo
## Created on: Tue Jul 21 23:28:41 中国标准时间 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
