######################################################################
##
## Filename: tb_sd.udo
## Created on: Mon Oct 14 15:10:55 中国标准时间 2019
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
